version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_RUN_PORT=5000
      - MYSQL_HOST=mysql
      - MYSQL_DB=restoapp_user
    depends_on:
      - mysql

  menu-service:
    build:
      context: .
      dockerfile: menu-service/Dockerfile
    ports:
      - "5002:5000"
    environment:
      - FLASK_RUN_PORT=5000
      - MYSQL_HOST=mysql
      - MYSQL_DB=restoapp_menu
    depends_on:
      - mysql

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "5003:5000"
    environment:
      - FLASK_RUN_PORT=5000
      - MYSQL_HOST=
      - MYSQL_DB=restoapp_order
    depends_on:
      - mysql

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "5004:5000"
    environment:
      - FLASK_RUN_PORT=5000
      - MYSQL_HOST=mysql
      - MYSQL_DB=restoapp_payment
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restoapp_user, restoapp_menu, restoapp_order, restoapp_payment
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql-data:
